AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:

  Function:
    Runtime: nodejs8.10
    Timeout: 5
    Handler: index.handler

Outputs:

  AuthenticationFunctionARN:
    Description: The ARN of the authentication function. It includes the version.
    Value: !Ref AuthenticationFunctionVersion

Resources:

  #
  # Functions
  #

  AuthenticationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Role:
        Fn::GetAtt: [ AuthenticationFunctionRole, Arn ]

  AuthenticationFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref AuthenticationFunction

  #
  # Roles
  #

  AuthenticationFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - "edgelambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
